name: "Pull Request"
description: 코드 변경 제안
title: "type(scope): "
labels: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: 무엇을 왜 변경했는지 간단히 작성
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Changes
      placeholder: |
        - 주요 변경 사항
        - 수정/추가된 로직
    validations:
      required: true

  - type: textarea
    id: test
    attributes:
      label: Test
      placeholder: |
        - 로컬 테스트 방법
        - 확인 결과
