[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "3dt-project"
version = "0.1.0"
dependencies = [
    "flask>=3.0",
    "psycopg2-binary>=2.9",
    "python-dotenv>=1.0",
]

[tool.setuptools.packages.find]
where = ["."]
namespaces = true
exclude = [
    ".venv*",
    "tests*",
    "data*",
    "docs*",
    "infra*",
    "notebooks*",
    "scripts*",
    "sql*",
    "artifacts*",
    "src.frontend.ios*"
]
