-- 목적: 크롤링 대상 동(수원시/용인시/평택시) 등록
-- 참고: dong_slug는 당근 URL의 in 파라미터 값(예: 망포동-4534)
--       슬러그 미입력(NULL) 행은 함수 실행 시 자동 스킵됩니다.

INSERT INTO daangn.target_dongs (city_name, dong_name, dong_slug, is_active)
VALUES
    -- 수원시
    ('수원시', '세류1동', NULL, TRUE),
    ('수원시', '세류2동', NULL, TRUE),
    ('수원시', '세류3동', NULL, TRUE),
    ('수원시', '평동', NULL, TRUE),
    ('수원시', '서둔동', NULL, TRUE),
    ('수원시', '구운동', NULL, TRUE),
    ('수원시', '금곡동', NULL, TRUE),
    ('수원시', '호매실동', NULL, TRUE),
    ('수원시', '권선1동', NULL, TRUE),
    ('수원시', '권선2동', NULL, TRUE),
    ('수원시', '곡선동', NULL, TRUE),
    ('수원시', '입북동', NULL, TRUE),
    ('수원시', '파장동', NULL, TRUE),
    ('수원시', '율천동', NULL, TRUE),
    ('수원시', '정자1동', NULL, TRUE),
    ('수원시', '정자2동', NULL, TRUE),
    ('수원시', '정자3동', NULL, TRUE),
    ('수원시', '영화동', NULL, TRUE),
    ('수원시', '송죽동', NULL, TRUE),
    ('수원시', '조원1동', NULL, TRUE),
    ('수원시', '조원2동', NULL, TRUE),
    ('수원시', '연무동', NULL, TRUE),
    ('수원시', '행궁동', NULL, TRUE),
    ('수원시', '매교동', NULL, TRUE),
    ('수원시', '매산동', NULL, TRUE),
    ('수원시', '고등동', NULL, TRUE),
    ('수원시', '화서1동', NULL, TRUE),
    ('수원시', '화서2동', NULL, TRUE),
    ('수원시', '지동', NULL, TRUE),
    ('수원시', '우만1동', NULL, TRUE),
    ('수원시', '우만2동', NULL, TRUE),
    ('수원시', '인계동', NULL, TRUE),
    ('수원시', '매탄1동', NULL, TRUE),
    ('수원시', '매탄2동', NULL, TRUE),
    ('수원시', '매탄3동', NULL, TRUE),
    ('수원시', '매탄4동', NULL, TRUE),
    ('수원시', '원천동', NULL, TRUE),
    ('수원시', '광교1동', NULL, TRUE),
    ('수원시', '광교2동', NULL, TRUE),
    ('수원시', '영통1동', NULL, TRUE),
    ('수원시', '영통2동', NULL, TRUE),
    ('수원시', '영통3동', NULL, TRUE),
    ('수원시', '망포동', '망포동-4534', TRUE),
    ('수원시', '망포1동', NULL, TRUE),
    ('수원시', '망포2동', NULL, TRUE),

    -- 용인시
    ('용인시', '포곡읍', NULL, TRUE),
    ('용인시', '모현읍', NULL, TRUE),
    ('용인시', '이동읍', NULL, TRUE),
    ('용인시', '남사읍', NULL, TRUE),
    ('용인시', '원삼면', NULL, TRUE),
    ('용인시', '백암면', NULL, TRUE),
    ('용인시', '양지면', NULL, TRUE),
    ('용인시', '중앙동', NULL, TRUE),
    ('용인시', '역북동', NULL, TRUE),
    ('용인시', '유림동', NULL, TRUE),
    ('용인시', '동부동', NULL, TRUE),
    ('용인시', '신갈동', NULL, TRUE),
    ('용인시', '영덕1동', NULL, TRUE),
    ('용인시', '영덕2동', NULL, TRUE),
    ('용인시', '구갈동', NULL, TRUE),
    ('용인시', '상갈동', NULL, TRUE),
    ('용인시', '보라동', NULL, TRUE),
    ('용인시', '기흥동', NULL, TRUE),
    ('용인시', '서농동', NULL, TRUE),
    ('용인시', '구성동', NULL, TRUE),
    ('용인시', '마북동', NULL, TRUE),
    ('용인시', '동백1동', NULL, TRUE),
    ('용인시', '동백2동', NULL, TRUE),
    ('용인시', '동백3동', NULL, TRUE),
    ('용인시', '상하동', NULL, TRUE),
    ('용인시', '보정동', NULL, TRUE),
    ('용인시', '풍덕천1동', NULL, TRUE),
    ('용인시', '풍덕천2동', NULL, TRUE),
    ('용인시', '신봉동', NULL, TRUE),
    ('용인시', '죽전1동', NULL, TRUE),
    ('용인시', '죽전2동', NULL, TRUE),
    ('용인시', '동천동', NULL, TRUE),
    ('용인시', '상현1동', NULL, TRUE),
    ('용인시', '상현2동', NULL, TRUE),
    ('용인시', '상현동', NULL, TRUE),
    ('용인시', '성복동', NULL, TRUE),

    -- 평택시
    ('평택시', '팽성읍', NULL, TRUE),
    ('평택시', '안중읍', NULL, TRUE),
    ('평택시', '포승읍', NULL, TRUE),
    ('평택시', '청북읍', NULL, TRUE),
    ('평택시', '진위면', NULL, TRUE),
    ('평택시', '서탄면', NULL, TRUE),
    ('평택시', '고덕면', NULL, TRUE),
    ('평택시', '오성면', NULL, TRUE),
    ('평택시', '현덕면', NULL, TRUE),
    ('평택시', '중앙동', NULL, TRUE),
    ('평택시', '서정동', NULL, TRUE),
    ('평택시', '송탄동', NULL, TRUE),
    ('평택시', '지산동', NULL, TRUE),
    ('평택시', '송북동', NULL, TRUE),
    ('평택시', '신평동', NULL, TRUE),
    ('평택시', '원평동', NULL, TRUE),
    ('평택시', '통복동', NULL, TRUE),
    ('평택시', '비전1동', NULL, TRUE),
    ('평택시', '비전2동', NULL, TRUE),
    ('평택시', '세교동', NULL, TRUE),
    ('평택시', '고덕동', NULL, TRUE),
    ('평택시', '동삭동', NULL, TRUE)
ON CONFLICT (city_name, dong_name)
DO UPDATE SET
    dong_slug = EXCLUDED.dong_slug,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();
