name: "Feature"
description: 기능 개발
title: "feat(scope): "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: 무엇을 변경하는지 간단히 작성
    validations:
      required: true
